name: love_app
description: "Proyecto de Amor App, a modo de prueba y aprendizaje"
publish_to: 'none'
version: 1.2.3+4

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  animate_do: ^3.1.2
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  go_router: ^13.0.1
  google_mobile_ads: ^4.0.0
  ionicons: ^0.2.2
  just_audio: ^0.9.36
  path_provider: ^2.1.2
  provider: ^6.1.1
  sqflite: ^2.3.0
  syncfusion_flutter_pdfviewer: ^24.1.47
  video_player: ^2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/love.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/love.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/love.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/love.png"

flutter:
  uses-material-design: true

  assets:
   - assets/images/
   - assets/videos/
   - assets/music/
   - assets/svg/

  fonts:
    - family: Bold
      fonts:
        - asset: assets/fonts/JosefinSans-Bold.ttf

    - family: SemiBold
      fonts:
        - asset: assets/fonts/JosefinSans-SemiBold.ttf

    - family: Medium
      fonts:
        - asset: assets/fonts/JosefinSans-Medium.ttf

    - family: Regular
      fonts:
        - asset: assets/fonts/JosefinSans-Regular.ttf

    - family: Light
      fonts:
        - asset: assets/fonts/JosefinSans-Light.ttf
